import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/Components/Hero/index'
import Navbar from "@/Components/Navbar/index"
import Cards from "@/Components/Cards/index"
import Community from "@/Components/Community/index"
const inter = Inter({ subsets: ['latin'] })
import Quotes from "@/Components/Quotes/index"
import Mission from "@/Components/Mission/index"
import Blogs from "@/Components/Blog/index";
import Member from "@/Components/Member/index"
import Footer from "@/Components/Footer/index"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero heading={"GIFTING LAND BACK TO NATURE"} description={"Join a community of like-minded people and businesses fighting to reverse biodiversity loss!"} />
      <Cards />
      <Community />
      <Quotes />
      <Mission />
      <Blogs />
      <Member />
      <Footer />
    </>
  )
}


